spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_order_system?autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB

logging:
  level:
    ROOT: INFO
    web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
